repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1 # Use the latest version or a specific one
    hooks:
    -   id: ruff
        args: [--fix] # Automatically fix fixable issues
    -   id: ruff-format # Run the formatter