repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9  # Use a more recent, stable version
    hooks:
    -   id: ruff
        args: [--fix, --unsafe-fixes]  # Automatically fix fixable issues
    -   id: ruff-format  # Run the formatterstat